version: 2.1

executors:
  sb_node:
    parameters:
      class:
        description: The Resource class
        type: enum
        enum: ['small', 'medium', 'large', 'xlarge']
        default: 'medium'
    working_directory: /tmp/storybook
    docker:
      - image: circleci/node:10-browsers
        environment:
          NODE_OPTIONS: --max_old_space_size=4096
    resource_class: <<parameters.class>>
  sb_node_12:
    parameters:
      class:
        description: The Resource class
        type: enum
        enum: ['small', 'medium', 'large', 'xlarge']
        default: 'medium'
    working_directory: /tmp/storybook
    docker:
      - image: circleci/node:12-browsers
        environment:
          NODE_OPTIONS: --max_old_space_size=4096
    resource_class: <<parameters.class>>

jobs:
  install:
    executor:
      class: large
      name: sb_node
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn install --frozen-lockfile --cache-folder ~/.cache/yarn
      - save_cache:
          name: Save Yarn cache
          key: build-yarn-cache-v1--{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn     
      - persist_to_workspace:
          root: .                 
  build:
    executor:
      class: large
      name: sb_node
    steps:
      - checkout
      - run:
          name: Build dependencies
          command: yarn build
  test:
    executor: sb_node
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Test
          command: yarn test
  lint:
    executor: sb_node
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Lint
          command: yarn lint
  publish:
    executor:
      class: large
      name: sb_node
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: running local registry
          command: yarn local-registry --publish
workflows:
  test:
    jobs:
      - install
      - build:
          requires:
            - install
      - lint:
          requires:
            - build            
      - test:
          requires:
            - build