version: 2.1

cache-defaults: &cache-defaults
  keys:
    - oid-v1-{{ arch }}-{{ checksum "yarn.lock" }}

aliases: 
  - &cache-modules
    key: oid-v1-{{ arch }}-{{ checksum "yarn.lock" }}
    paths: &cache-modules-paths
      - ~/.cache/yarn
      - node_modules
      - packages/appetize-utils/node_modules
      - packages/native/node_modules
      - packages/native-addon/node_modules
      - packages/native-components/node_modules
      - packages/native-devices/node_modules
      - packages/native-types/node_modules
      # Necessary so that linting is faster on CI
      - .eslintcache
  - &yarn
    name: Installing Dependencies
    command: yarn install --non-interactive --frozen-lockfile --cache-folder ~/.cache/yarn

executors:
  sb_node:
    parameters:
      class:
        description: The Resource class
        type: enum
        enum: ['small', 'medium', 'large', 'xlarge']
        default: 'medium'
    working_directory: /tmp/storybook
    docker:
      - image: circleci/node:10-browsers
        environment:
          NODE_OPTIONS: --max_old_space_size=4096
    resource_class: <<parameters.class>>
  sb_node_12:
    parameters:
      class:
        description: The Resource class
        type: enum
        enum: ['small', 'medium', 'large', 'xlarge']
        default: 'medium'
    working_directory: /tmp/storybook
    docker:
      - image: circleci/node:12-browsers
        environment:
          NODE_OPTIONS: --max_old_space_size=4096
    resource_class: <<parameters.class>>

jobs:
  build:
    executor:
      class: large
      name: sb_node
    steps:
      - checkout
      - restore_cache:
          <<: *cache-defaults
      - run: *yarn
      - run:
          name: Build
          command: yarn build
      - run:
          name: Build storybooks
          command: yarn build:storybook
      - save_cache: *cache-modules

  test:
    executor: sb_node
    steps:
      - checkout
      - attach_workspace:
          at: .
      - restore_cache:
          <<: *cache-defaults
      - run: *yarn
      - run:
          name: Test
          command: yarn test
  lint:
    executor: sb_node
    steps:
      - checkout
      - attach_workspace:
          at: .
      - restore_cache:
          <<: *cache-defaults
      - run: *yarn
      - run:
          name: Lint
          command: yarn lint --cache
      - run:
          name: Prettier
          command: yarn prettier
      - save_cache: *cache-modules
  release:
    executor: sb_node
    steps:
      - checkout
      - attach_workspace:
          at: .
      - restore_cache:
          <<: *cache-defaults
      - run: *yarn
      - run:
          name: Build
          command: yarn build
      - run:
          name: Assume Github Role
          command: 'git config --global user.email "vasikarla.raj@gmail.com" && git config --global user.name "vasikarla"'
      - run:
          name: Auto Shipit
          command: |
            yarn release
            bash ./deploy.sh
workflows:
  test:
    jobs:
      - build
      - lint:
          requires:
            - build            
      - test:
          requires:
            - build
      - release:
          requires:
            - test
            - lint          
