version: 2.1

defaults: &defaults
  working_directory: ~/storybook-native
  docker:
    - image: circleci/node:10-browsers
  environment:
    TZ: "/usr/share/zoneinfo/America/Los_Angeles"

    aliases:
  # Circle related commands
  - &restore-cache
    keys:
      # Find a cache corresponding to this specific package.json checksum
      # when this file is changed, this key will fail
      - storybook-native-{{ checksum "yarn.lock" }}-{{ checksum ".circleci/config.yml" }}
      - storybook-native-{{ checksum "yarn.lock" }}
      # Find the most recent cache used from any branch
      - storybook-native-
  - &save-cache
    key: storybook-native-{{ checksum "yarn.lock" }}-{{ checksum ".circleci/config.yml" }}
    paths:
      - ~/.cache/yarn
      - node_modules
  # Yarn commands
  - &yarn
    name: Install Dependencies
    command: yarn install --frozen-lockfile --non-interactive
  - &build
    name: Build
    command: yarn build

jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - restore_cache: *restore-cache
      - run: *yarn
      - save_cache: *save-cache
      - persist_to_workspace:
          root: .
          paths:
            - .    