version: 2

jobs:
  lint:
    docker:
      - image: circleci/node:12
    working_directory: ~//tmp/storybook-native
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: yarn install
      - run: yarn lint
  build:
    docker:
      - image: circleci/node:12
    working_directory: ~//tmp/storybook-native
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn build

workflows:
  version: 2
  lint-build:
    jobs:
      - build